title       = "opentargets"
baseURL     = "https://opentargets-cli.tamnd.com/"
description = "A command line for opentargets."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/opentargets-cli"
